version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./app
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
  mysql:
    image: elestio/mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 172.17.0.1:42401:3306
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 172.17.0.1:56127:80
    volumes:
      - ./app:/var/www
      - ./nginx:/etc/nginx/conf.d/

  pma:
    image: elestio/phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - "172.17.0.1:39553:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 500M
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
