version: "3"
services:
  app:
    image: "php:8.3-fpm"
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
  web:
    image: "nginx:latest"
    ports:
      - "172.17.0.1:56127:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  mysql:
    image: "elestio/mysql:8.0"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  redis:
    image: "elestio/redis:7.0"
  worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
